version: '3.8'

x-common-variables:
  MONGO_IMAGE: &mongo_image mongo:8

services:
  mongo1:
    container_name: mongo-to-mongo-example
    hostname: mongo1
    image: *mongo_image
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./scripts:/opt/scripts
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    command: mongod --replSet mstream_replica_set --bind_ip_all --keyFile /opt/scripts/mongo-keyfile
    networks:
      - mongo_network

networks:
  mongo_network:
    name: mongo_network

volumes:
  mongo_data:
